import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  app: {
    minHeight: "100dvh",
    display: "flex",
    flexDirection: "column",
    background: "linear-gradient(135deg, #0a0a0f 0%, #0f0f1a 50%, #0a0f0a 100%)",
  },
  header: {
    borderBottom: "1px solid #1e2a3a",
    backdropFilter: "blur(10px)",
    background: "rgba(10, 10, 15, 0.8)",
    position: "sticky",
    top: 0,
    zIndex: 50,
  },
  headerInner: {
    maxWidth: 720,
    margin: "0 auto",
    padding: "14px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brand: { display: "flex", alignItems: "center", gap: 10 },
  brandIcon: { fontSize: 20 },
  brandName: { fontWeight: 700, fontSize: 18, color: "#e2e8f0", letterSpacing: "-0.02em" },
  brandBadge: {
    fontSize: 10,
    fontWeight: 700,
    background: "linear-gradient(135deg, #4ade80, #22d3ee)",
    color: "#000",
    padding: "2px 6px",
    borderRadius: 4,
    letterSpacing: "0.05em",
  },
  main: { flex: 1, padding: "24px 20px" },
  container: { maxWidth: 720, margin: "0 auto" },
  hero: {
    textAlign: "center",
    padding: "60px 20px",
  },
  heroIcon: { fontSize: 64, marginBottom: 20 },
  heroTitle: {
    fontSize: 28,
    fontWeight: 700,
    color: "#e2e8f0",
    marginBottom: 12,
    letterSpacing: "-0.03em",
  },
  heroSubtitle: {
    color: "#64748b",
    fontSize: 15,
    lineHeight: 1.7,
    marginBottom: 40,
  },
  features: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: 12,
    maxWidth: 520,
    margin: "0 auto",
  },
  featureCard: {
    background: "#111827",
    border: "1px solid #1e293b",
    borderRadius: 12,
    padding: "16px 12px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    fontSize: 13,
    color: "#94a3b8",
  },
  featureIcon: { fontSize: 24 },
  footer: {
    textAlign: "center",
    padding: "16px 20px",
    fontSize: 12,
    color: "#334155",
    borderTop: "1px solid #111827",
  },
};
